# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_prueba',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/nbdev_prueba',
                'lib_path': 'nbdev_prueba'},
  'syms': {'nbdev_prueba.core': {'nbdev_prueba.core.foo': ('core.html#foo', 'nbdev_prueba/core.py')}}}
